version: '4'
services:
  postgres:
    image: postgres:15-alpine
    container_name: psg01
    restart: always
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "postgres", "-p", "5432", "-U", "dev-user", "-d", "dev_db"]
      interval: 10s
      retries: 3
    networks:
      - ArqivaTest
    # Uncomment to persist database
    #    volumes:
    #      - postgres-data:/var/lib/postgresql/data

#  app:
#    container_name: app
#    build: .
#    # Uncomment to persist database
##    volumes:
##      - app-data:/app
#    restart: always
#    depends_on:
#      spark-master
#      spark-worker
#      postgres:
#        condition: service_healthy
#    command:  python main.py --watch 'imports'
#    networks:
#      - ArqivaTest

#  spark-master:
#    build: .
#    container_name: spark-master
#    ports:
#      - "8080:8080"  # Spark Master UI
#      - "7077:7077"  # Spark Master Port
#    environment:
#      - SPARK_MODE=master
#    networks:
#      - ArqivaTest
#
#  spark-worker:
#      build: .
#      container_name: spark-worker
#      depends_on:
#        - spark-master
#      environment:
#        - SPARK_MODE=worker
#        - SPARK_MASTER=spark://spark-master:7077
#      networks:
#        - ArqivaTest
#      ports:
#        - "8081:8081"  # Spark Worker UI
#

networks:
    ArqivaTest:
      driver: bridge

# Uncomment to persist database
volumes:
  spark-logs:
#  postgres-data:
#  app-data